import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import admin from "firebase-admin";
import { getFirestore } from "firebase-admin/firestore";
import cors from "cors";
import dotenv from "dotenv";
import fs from "fs";
import { Pool } from "pg";

// Load .env.local if it exists, otherwise default .env
if (fs.existsSync(path.join(process.cwd(), ".env.local"))) {
  dotenv.config({ path: path.join(process.cwd(), ".env.local") });
}
dotenv.config();

const firebaseConfig = JSON.parse(fs.readFileSync(path.join(process.cwd(), "firebase-applet-config.json"), "utf8"));

// Initialize Firebase Admin for Authentication and Firestore
if (!admin.apps.length) {
  admin.initializeApp({
    projectId: firebaseConfig.projectId,
  });
}

const db = getFirestore(undefined, firebaseConfig.firestoreDatabaseId);

function requiredEnv(name: string): string {
  const value = process.env[name];
  if (!value) {
    throw new Error(`Missing required env var: ${name}`);
  }
  return value;
}

function optionalEnv(name: string, fallback = ''): string {
  return process.env[name] || fallback;
}

let connectionString = process.env.DATABASE_URL;

if (!connectionString && process.env.SUPABASE_URL) {
  const projectUrl = process.env.SUPABASE_URL;
  const match = projectUrl.match(/https?:\/\/([^.]+)\.supabase\.co/);
  if (match) {
    const projectRef = match[1];
    const dbPassword = process.env.SUPABASE_DB_PASSWORD || process.env.VPS_SSH_PASSWORD || process.env.GOWA_PASSWORD || 'Master120221@@@';
    connectionString = `postgresql://postgres:${encodeURIComponent(dbPassword)}@db.${projectRef}.supabase.co:5432/postgres`;
  }
}

const pgPool = connectionString ? new Pool({
  connectionString,
  ssl: { rejectUnauthorized: false }
}) : null;

// Initialize PG Tables if possible
if (pgPool) {
  pgPool.query(`
    CREATE TABLE IF NOT EXISTS user_settings (
      uid TEXT PRIMARY KEY,
      persona_name TEXT DEFAULT 'Beatrice',
      user_call_name TEXT DEFAULT 'Boss',
      system_prompt TEXT,
      voice TEXT DEFAULT 'Kore',
      language TEXT DEFAULT 'English'
    );
  `).catch(err => console.error("Could not init PG user_settings table", err));

  pgPool.query(`
    CREATE TABLE IF NOT EXISTS user_memories (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      uid TEXT NOT NULL,
      content TEXT NOT NULL,
      type TEXT DEFAULT 'personal',
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
  `).catch(err => console.error("Could not init PG user_memories table", err));

  pgPool.query(`
    CREATE TABLE IF NOT EXISTS user_conversations (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      uid VARCHAR(255) NOT NULL,
      session_id VARCHAR(255),
      role VARCHAR(50) NOT NULL,
      content TEXT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
  `).catch(err => console.error("Could not init PG user_conversations table", err));

  pgPool.query(`
    CREATE TABLE IF NOT EXISTS whatsapp_messages (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      phone VARCHAR(50) NOT NULL,
      sender_name VARCHAR(255),
      message_id VARCHAR(255) NOT NULL,
      text TEXT,
      from_me BOOLEAN DEFAULT FALSE,
      timestamp BIGINT NOT NULL,
      created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
    );
  `).catch(err => console.error("Could not init PG whatsapp_messages table", err));
}

async function startServer() {
  const app = express();
  const PORT = process.env.PORT ? parseInt(process.env.PORT) : 4343;

  app.use(express.json());
  app.use(cors());

  // Logging middleware
  app.use((req, res, next) => {
    console.log(`${new Date().toISOString()} - ${req.method} ${req.url}`);
    next();
  });

  // Health check
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok", message: "Server is running", dbConnected: true });
  });

  // Beatrice Avatar Endpoint
  app.get("/api/avatar", (req, res) => {
    const fs = require('fs');
    const path = require('path');
    const sourcePath = '/Users/eburon/.gemini/antigravity/brain/d30ce24b-f80e-41c9-974d-fde1f0ff87b6/beatrice_avatar_1779190854412.png';
    // Copy to root workspace relative to server location
    const localDest = path.join(process.cwd(), 'beatrice-avatar.png');
    
    if (fs.existsSync(sourcePath)) {
      try {
        if (!fs.existsSync(localDest)) {
          fs.copyFileSync(sourcePath, localDest);
        }
      } catch (e) {
        console.warn("Failed to copy avatar:", e);
      }
      return res.sendFile(sourcePath);
    }
    
    if (fs.existsSync(localDest)) {
      return res.sendFile(localDest);
    }
    
    res.status(404).send('Avatar not found');
  });

  app.get("/healthz", (req, res) => {
    res.json({ ok: true, service: "eburon-backend" });
  });

  app.get("/api/healthz", (req, res) => {
    res.json({ ok: true, service: "eburon-backend" });
  });

  // Middleware to verify Firebase Auth Token
  const authenticateToken = async (req: any, res: any, next: any) => {
    const authHeader = req.headers['authorization'];
    const token = authHeader && authHeader.split(' ')[1];

    if (!token) {
      console.log("No token provided in request");
      return res.status(401).json({ error: "Unauthorized: No token provided" });
    }

    try {
      if (!admin.apps.length) {
         return res.status(500).json({ error: "Firebase Admin not initialized" });
      }
      const decodedToken = await admin.auth().verifyIdToken(token);
      req.user = decodedToken;
      next();
    } catch (err: any) {
      console.error("Token verification error:", err.message);
      return res.status(403).json({ error: "Forbidden: Invalid token", details: err.message });
    }
  };


  const artifactRoot = path.join(process.cwd(), "artifacts");
  const notesRoot = path.join(process.cwd(), "notes");
  fs.mkdirSync(artifactRoot, { recursive: true });
  fs.mkdirSync(notesRoot, { recursive: true });

  const sanitizeFileName = (value: string, fallback: string, extension?: string) => {
    const cleaned = String(value || fallback)
      .replace(/\\/g, "/")
      .split("/")
      .pop()!
      .replace(/[^a-zA-Z0-9._-]/g, "-")
      .replace(/-+/g, "-")
      .slice(0, 120) || fallback;
    if (extension && !cleaned.endsWith(extension)) return `${cleaned}${extension}`;
    return cleaned;
  };

  const writeTextArtifact = (uid: string, filename: string, content: string) => {
    const userDir = path.join(artifactRoot, uid);
    fs.mkdirSync(userDir, { recursive: true });
    const safeName = sanitizeFileName(filename, `artifact-${Date.now()}.txt`);
    const filePath = path.join(userDir, safeName);
    fs.writeFileSync(filePath, content, "utf8");
    return {
      ok: true,
      status: "completed",
      artifact: {
        filename: safeName,
        path: path.relative(process.cwd(), filePath),
      },
    };
  };

  const renderList = (items: any[] = [], prefix = "- ") => items.map(item => `${prefix}${String(item)}`).join("\n");

  app.post("/api/local-tools/run", authenticateToken, async (req: any, res) => {
    try {
      const { uid } = req.user;
      const { name, args } = req.body || {};
      const input = args || {};
      let result: any;

      switch (name) {
        case "create_markdown_document": {
          const filename = sanitizeFileName(input.filename, "document.md", ".md");
          result = writeTextArtifact(uid, filename, `# ${input.title || "Untitled"}\n\n${input.content || ""}\n`);
          break;
        }
        case "create_html_document": {
          const filename = sanitizeFileName(input.filename, "document.html", ".html");
          const title = input.title || "Untitled";
          const body = input.body || "";
          const html = `<!doctype html>\n<html lang="en">\n<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><style>body{font-family:system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:900px;margin:40px auto;padding:0 20px;line-height:1.6;color:#111827}pre,code{background:#f3f4f6;border-radius:6px;padding:2px 5px}pre{padding:16px;overflow:auto}table{border-collapse:collapse;width:100%}td,th{border:1px solid #d1d5db;padding:8px}</style></head>\n<body><h1>${title}</h1>\n${body}\n</body></html>\n`;
          result = writeTextArtifact(uid, filename, html);
          break;
        }
        case "create_project_brief": {
          const projectName = input.project_name || "Project";
          const content = `# ${projectName} — Project Brief\n\n## Goal\n\n${input.goal || "Not specified."}\n\n## Audience\n\n${input.audience || "Not specified."}\n\n## Features\n\n${renderList(input.features || ["Not specified."])}\n\n## Risks\n\n${renderList(input.risks || ["Not specified."])}\n\n## Next Steps\n\n${renderList((input.next_steps || ["Define next steps."]).map((x: string) => `[ ] ${x}`), "- ")}\n`;
          result = writeTextArtifact(uid, sanitizeFileName(`${projectName}-brief.md`, "project-brief.md", ".md"), content);
          break;
        }
        case "create_checklist": {
          const filename = sanitizeFileName(input.filename, "checklist.md", ".md");
          const content = `# ${input.title || "Checklist"}\n\n${renderList((input.items || []).map((x: string) => `[ ] ${x}`), "- ")}\n`;
          result = writeTextArtifact(uid, filename, content);
          break;
        }
        case "save_note": {
          const userDir = path.join(notesRoot, uid);
          fs.mkdirSync(userDir, { recursive: true });
          const filename = sanitizeFileName(input.name, "note.txt", ".txt");
          const filePath = path.join(userDir, filename);
          fs.writeFileSync(filePath, String(input.content || ""), "utf8");
          result = { ok: true, status: "completed", note: { filename, path: path.relative(process.cwd(), filePath) } };
          break;
        }
        case "read_note": {
          const filename = sanitizeFileName(input.name, "note.txt", ".txt");
          const filePath = path.join(notesRoot, uid, filename);
          if (!fs.existsSync(filePath)) return res.status(404).json({ ok: false, error: `Note not found: ${filename}` });
          result = { ok: true, filename, content: fs.readFileSync(filePath, "utf8") };
          break;
        }
        case "list_notes": {
          const userDir = path.join(notesRoot, uid);
          fs.mkdirSync(userDir, { recursive: true });
          result = { ok: true, notes: fs.readdirSync(userDir).filter(name => name.endsWith(".txt")) };
          break;
        }
        case "create_json_file": {
          const filename = sanitizeFileName(input.filename, "data.json", ".json");
          const parsed = typeof input.data === "string" ? JSON.parse(input.data) : input.data;
          result = writeTextArtifact(uid, filename, JSON.stringify(parsed, null, 2));
          break;
        }
        case "validate_json": {
          JSON.parse(input.json_text || "");
          result = { ok: true, valid: true };
          break;
        }
        case "create_env_template": {
          const filename = sanitizeFileName(input.filename, ".env.example");
          const lines = (input.variables || []).map((variable: string) => {
            const key = String(variable).toUpperCase().replace(/[^A-Z0-9_]/g, "");
            if (!key) return "";
            return /KEY|SECRET|PASSWORD|TOKEN|SERVICE_ROLE/.test(key) ? `${key}=replace_me` : `${key}=`;
          }).filter(Boolean).join("\n") + "\n";
          result = writeTextArtifact(uid, filename, lines);
          break;
        }
        case "create_readme": {
          const content = `# ${input.project_name || "Project"}\n\n${input.description || ""}\n\n## Features\n\n${renderList(input.features || ["Not specified."])}\n\n## Installation\n\n${(input.install_steps || ["No installation steps provided."]).map((x: string, i: number) => `${i + 1}. ${x}`).join("\n")}\n\n## Run\n\n${(input.run_steps || ["No run steps provided."]).map((x: string, i: number) => `${i + 1}. ${x}`).join("\n")}\n`;
          result = writeTextArtifact(uid, "README.md", content);
          break;
        }
        case "create_chart_spec": {
          if ((input.labels || []).length !== (input.values || []).length) throw new Error("labels and values must have the same length.");
          const spec = { chartType: input.chart_type, title: input.title, data: (input.labels || []).map((label: string, i: number) => ({ label, value: input.values[i] })) };
          result = writeTextArtifact(uid, sanitizeFileName(input.filename, "chart.json", ".json"), JSON.stringify(spec, null, 2));
          break;
        }
        case "extract_tasks": {
          const markers = ["todo", "to do", "fix", "add", "create", "build", "update", "remove", "check", "test", "deploy", "install"];
          const tasks = String(input.source_text || "").split(/\r?\n/).map((line: string) => line.replace(/^[-*•\s]+/, "").trim()).filter((line: string) => line && markers.some(marker => line.toLowerCase().includes(marker)));
          result = writeTextArtifact(uid, sanitizeFileName(input.filename, "tasks.md", ".md"), `# Extracted Tasks\n\n${renderList((tasks.length ? tasks : ["Review source text and define action items."]).map((x: string) => `[ ] ${x}`), "- ")}\n`);
          break;
        }
        case "create_video_storyboard":
        case "create_video_script_document":
        case "create_deployment_video_plan":
        case "register_google_video_asset":
        case "register_google_site_asset":
        case "create_site_content_plan":
        case "create_deployment_portal_copy":
        case "create_restaurant_demo_site_copy": {
          const filename = sanitizeFileName(`${name}-${Date.now()}.json`, "beatrice-asset.json", ".json");
          result = writeTextArtifact(uid, filename, JSON.stringify({ tool: name, data: input, createdAt: new Date().toISOString() }, null, 2));
          break;
        }
        default:
          return res.status(400).json({ ok: false, error: `Unknown local tool: ${name}` });
      }

      res.json(result);
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err.message });
    }
  });

  app.post("/api/tools/apps-script/run", authenticateToken, async (req: any, res) => {
    try {
      const webAppUrl = requiredEnv("GOOGLE_APPS_SCRIPT_WEBAPP_URL");
      const secret = requiredEnv("GOOGLE_APPS_SCRIPT_TOOL_SECRET");
      const { action, payload } = req.body || {};
      const allowedActions = new Set(["ping", "create_doc", "append_sheet_row", "read_sheet_range", "create_calendar_event", "create_gmail_draft", "send_gmail_email", "create_drive_folder", "create_deployment_report", "log_deployment_status", "check_health_url"]);
      if (!action || !allowedActions.has(action)) {
        return res.status(400).json({ ok: false, error: "Invalid or missing Apps Script action." });
      }
      const response = await fetch(webAppUrl, {
        method: "POST",
        headers: { "Content-Type": "text/plain;charset=utf-8" },
        body: JSON.stringify({ secret, action, payload: payload || {} }),
      });
      const text = await response.text();
      let data: any;
      try { data = JSON.parse(text); } catch { data = { ok: false, raw: text }; }
      res.status(response.ok ? 200 : response.status).json(data);
    } catch (err: any) {
      res.status(500).json({ ok: false, error: err.message });
    }
  });

  // API Routes
  
  // Settings
  app.get("/api/settings", authenticateToken, async (req: any, res) => {
    try {
      const { uid } = req.user;

      if (pgPool) {
        try {
          const result = await pgPool.query(
            "SELECT * FROM user_settings WHERE uid = $1",
            [uid]
          );
          if (result.rows.length > 0) {
            return res.json(result.rows[0]);
          } else {
            const defaultSettings = { persona_name: 'Beatrice', language: 'English', voice: 'Kore', user_call_name: 'Boss' };
            await pgPool.query(
              "INSERT INTO user_settings (uid, persona_name, user_call_name, voice, language) VALUES ($1, $2, $3, $4, $5)",
              [uid, defaultSettings.persona_name, defaultSettings.user_call_name, defaultSettings.voice, defaultSettings.language]
            );
            return res.json({ uid, ...defaultSettings });
          }
        } catch (e) {
          console.error("PG Settings Read error, falling back to Firestore", e);
        }
      }

      const userSettingsRef = db.collection('user_settings').doc(uid);
      const doc = await userSettingsRef.get();

      if (!doc.exists) {
        // No results, insert default settings.
        const defaultSettings = { persona_name: 'Beatrice', language: 'English' };
        await userSettingsRef.set(defaultSettings);
        return res.json(defaultSettings);
      }
      
      res.json(doc.data());
    } catch (err: any) {
      console.error("Settings GET catch error:", err);
      res.status(500).json({ error: "Internal server error: " + err.message });
    }
  });

  app.put("/api/settings", authenticateToken, async (req: any, res) => {
    try {
      const { uid } = req.user;
      const { persona_name, user_call_name, system_prompt, voice, language } = req.body;
      
      const payload: any = {
        persona_name,
        user_call_name,
        system_prompt,
        voice,
        language
      };
      
      // Clean undefined values
      Object.keys(payload).forEach(key => payload[key] === undefined && delete payload[key]);

      if (pgPool) {
        try {
          const checkRes = await pgPool.query("SELECT 1 FROM user_settings WHERE uid = $1", [uid]);
          if (checkRes.rows.length > 0) {
            const sets: string[] = [];
            const vals: any[] = [uid];
            let valIdx = 2;
            for (const [k, v] of Object.entries(payload)) {
              sets.push(`${k} = $${valIdx++}`);
              vals.push(v);
            }
            if (sets.length > 0) {
              await pgPool.query(
                `UPDATE user_settings SET ${sets.join(", ")} WHERE uid = $1`,
                vals
              );
            }
          } else {
            const cols = ['uid'];
            const placeholders = ['$1'];
            const vals = [uid];
            let valIdx = 2;
            for (const [k, v] of Object.entries(payload)) {
              cols.push(k);
              placeholders.push(`$${valIdx++}`);
              vals.push(v);
            }
            await pgPool.query(
              `INSERT INTO user_settings (${cols.join(", ")}) VALUES (${placeholders.join(", ")})`,
              vals
            );
          }
        } catch (e) {
          console.error("PG Settings Write error", e);
        }
      }

      await db.collection('user_settings').doc(uid).set(payload, { merge: true });
      const updatedDoc = await db.collection('user_settings').doc(uid).get();
      
      res.json(updatedDoc.data());
    } catch (err: any) {
      console.error("Settings PUT error:", err);
      res.status(500).json({ error: "Internal server error: " + err.message });
    }
  });

  // Conversations
  app.get("/api/conversations", authenticateToken, async (req: any, res) => {
    try {
      const { uid } = req.user;
      const limitAmt = Number(req.query.limit) || 100;
      
      if (pgPool) {
        try {
          const result = await pgPool.query(
            "SELECT * FROM user_conversations WHERE uid = $1 ORDER BY created_at DESC LIMIT $2",
            [uid, limitAmt]
          );
          const data = result.rows.map(row => ({
            id: row.id.toString(),
            uid: row.uid,
            session_id: row.session_id,
            role: row.role,
            content: row.content,
            created_at: row.created_at
          }));
          return res.json(data ? data.reverse() : []);
        } catch (e) {
          console.error("PG Read sync error", e);
        }
      }

      const snapshot = await db.collection('user_conversations')
        .where('uid', '==', uid)
        .orderBy('created_at', 'desc')
        .limit(limitAmt)
        .get();

      const data = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      res.json(data ? data.reverse() : []);
    } catch (err: any) {
      console.error("Fetch conversations error:", err.message);
      
      // If index is missing, return empty instead of failing
      if (err.message.includes('FAILED_PRECONDITION')) {
          return res.json([]);
      }
      res.status(500).json({ error: err.message });
    }
  });

  app.post("/api/conversations", authenticateToken, async (req: any, res) => {
    try {
      const { uid } = req.user;
      const { role, content, session_id } = req.body;

      if (!role || !content) {
        return res.status(400).json({ error: "Missing role or content" });
      }

      // 1) Save to Postgres
      if (pgPool) {
        try {
          await pgPool.query(
            "INSERT INTO user_conversations (uid, session_id, role, content) VALUES ($1, $2, $3, $4)",
            [uid, session_id || 'default', role, content]
          );
        } catch (e) {
          console.error("PG Sync Error", e);
        }
      }

      // 2) Save to Firebase (acts as standard local cloud edge backup here)
      const docRef = await db.collection('user_conversations').add({
        uid,
        role,
        content,
        session_id: session_id || 'default',
        created_at: admin.firestore.FieldValue.serverTimestamp()
      });

      const doc = await docRef.get();
      res.json({ id: doc.id, ...doc.data() });
    } catch (err: any) {
      console.error("Save conversation turn error:", err.message);
      res.status(500).json({ error: err.message });
    }
  });

  // Memories
  app.get("/api/memories", authenticateToken, async (req: any, res) => {
    try {
      const { uid } = req.user;

      if (pgPool) {
        try {
          const result = await pgPool.query(
            "SELECT * FROM user_memories WHERE uid = $1 ORDER BY created_at DESC",
            [uid]
          );
          const data = result.rows.map(row => ({
            id: row.id.toString(),
            uid: row.uid,
            content: row.content,
            type: row.type,
            created_at: row.created_at
          }));
          return res.json(data);
        } catch (e) {
          console.error("PG Memories GET error", e);
        }
      }

      const snapshot = await db.collection('user_memories')
        .where('uid', '==', uid)
        .orderBy('created_at', 'desc')
        .get();

      const data = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      res.json(data);
    } catch (err: any) {
      console.error("Memories GET error:", err);
      // If index is missing, return empty instead of failing
      if (err.message.includes('FAILED_PRECONDITION')) {
          return res.json([]);
      }
      res.status(500).json({ error: "Internal server error: " + err.message });
    }
  });

  app.post("/api/memories", authenticateToken, async (req: any, res) => {
    try {
      const { uid } = req.user;
      const { content, type = 'personal' } = req.body;

      if (!content) {
        return res.status(400).json({ error: "Missing 'content' in request body" });
      }
      
      let pgId = null;
      if (pgPool) {
        try {
          const result = await pgPool.query(
            "INSERT INTO user_memories (uid, content, type) VALUES ($1, $2, $3) RETURNING id",
            [uid, content, type]
          );
          pgId = result.rows[0].id.toString();
        } catch (e) {
          console.error("PG Memories POST error", e);
        }
      }

      const docRef = await db.collection('user_memories').add({
        uid,
        content,
        type,
        created_at: admin.firestore.FieldValue.serverTimestamp()
      });

      const doc = await docRef.get();
      res.json({ id: pgId || doc.id, ...doc.data() });
    } catch (err: any) {
      console.error("Memories POST catch error:", err);
      res.status(500).json({ error: "Internal server error: " + err.message });
    }
  });

  app.delete("/api/memories/:id", authenticateToken, async (req: any, res) => {
    try {
      const { id } = req.params;
      const { uid } = req.user;
      
      if (pgPool) {
        try {
          await pgPool.query(
            "DELETE FROM user_memories WHERE (id = $1 OR id::text = $1) AND uid = $2",
            [id, uid]
          );
        } catch (e) {
          console.error("PG Memories DELETE error", e);
        }
      }

      const docRef = db.collection('user_memories').doc(id);
      const doc = await docRef.get();
      
      if (doc.exists && doc.data()?.uid === uid) {
          await docRef.delete();
      }
      
      res.json({ status: "success" });
    } catch (err: any) {
      console.error("Memories DELETE error:", err);
      res.status(500).json({ error: "Internal server error: " + err.message });
    }
  });

  // Storage Example Endpoint (if user wants to upload something)
  app.post("/api/upload", authenticateToken, async (req: any, res) => {
     res.status(501).json({ error: "Storage endpoint not fully implemented. Requires multipart/form-data handling." });
  });

  // System commands
  app.get("/api/system_command", async (req: any, res: any) => {
    try {
      // Intentionally omitting authenticateToken strictly for demo purposes, or we could require it.
      // Eburon demo sometimes doesn't send the proper token over yet. Let's make it allow for local demo.
      const cmd = req.query.cmd;
      const allowed = ["date", "uptime", "hostname", "pwd", "whoami", "ls"];
      if (!allowed.includes(cmd)) {
         return res.status(403).json({ error: "Command not allowed. Allowed cmds: " + allowed.join(", ") });
      }
      
      const { exec } = require('child_process');
      exec(cmd, (error: any, stdout: any, stderr: any) => {
          if (error) {
              return res.json({ error: error.message, stderr });
          }
          res.json({ stdout: stdout.trim(), stderr: stderr ? stderr.trim() : '' });
      });
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Search API
  app.get("/api/search", authenticateToken, async (req: any, res) => {
    try {
      const { q } = req.query;
      if (!q) {
        return res.status(400).json({ error: "Missing query parameter 'q'" });
      }

      const apiKey = process.env.GOOGLE_SEARCH_API_KEY;
      const cx = process.env.GOOGLE_SEARCH_CX;

      if (!apiKey || !cx) {
        console.warn("Search API keys missing. Returning empty results.");
        return res.status(503).json({ 
          error: "Google Search API is not configured. Please add GOOGLE_SEARCH_API_KEY and GOOGLE_SEARCH_CX to your environment variables.",
          results: [] 
        });
      }

      const searchUrl = `https://www.googleapis.com/customsearch/v1?key=${apiKey}&cx=${cx}&q=${encodeURIComponent(q as string)}`;
      const response = await fetch(searchUrl);
      
      if (!response.ok) {
        const errData = await response.json().catch(() => ({}));
        throw new Error(`Google Search API error: ${response.status} ${JSON.stringify(errData)}`);
      }

      const data = await response.json();
      const results = (data.items || []).map((item: any) => ({
        title: item.title,
        snippet: item.snippet,
        link: item.link
      }));

      res.json({ results });
    } catch (err: any) {
      console.error("Search API error:", err.message);
      res.status(500).json({ error: err.message, results: [] });
    }
  });

  // ──────────────────────────────────────────────
  // WhatsApp GoWA API Router (multi-user)
  // ──────────────────────────────────────────────

  const getGoWAHeaders = (uid: string) => {
    const apiUrl = requiredEnv("GOWA_API_URL");
    const username = requiredEnv("GOWA_USERNAME");
    const password = requiredEnv("GOWA_PASSWORD");
    const deviceId = `wa_${uid.substring(0, 12)}`;
    const authHeader = "Basic " + Buffer.from(`${username}:${password}`).toString("base64");
    return { apiUrl, deviceId, authHeader };
  };

  const proxyGet = (path: string, gowaPathTransform?: (req: any) => string) => async (req: any, res: any) => {
    try {
      const { apiUrl, deviceId, authHeader } = getGoWAHeaders(req.user.uid);
      const goPath = gowaPathTransform ? gowaPathTransform(req) : path;
      const params = new URLSearchParams();
      for (const [k, v] of Object.entries(req.query)) {
        if (v !== undefined) params.set(k, v as string);
      }
      const qs = params.toString();
      const response = await fetch(`${apiUrl}${goPath}${qs ? '?' + qs : ''}`, {
        headers: { "Authorization": authHeader, "X-Device-Id": deviceId }
      });
      const data = await response.json();
      res.json(data);
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  };

  const proxyPost = (path: string, gowaPathTransform?: (req: any) => string) => async (req: any, res: any) => {
    try {
      const { apiUrl, deviceId, authHeader } = getGoWAHeaders(req.user.uid);
      const goPath = gowaPathTransform ? gowaPathTransform(req) : path;
      const response = await fetch(`${apiUrl}${goPath}`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": authHeader,
          "X-Device-Id": deviceId
        },
        body: JSON.stringify(req.body)
      });
      const data = await response.json();
      res.json(data);
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  };

  const proxyMultipart = (gowaPath: string, fields: string[], fileField: string) => async (req: any, res: any) => {
    try {
      const { apiUrl, deviceId, authHeader } = getGoWAHeaders(req.user.uid);
      const { phone, ...rest } = req.body;
      if (!phone || !rest[fileField]) {
        return res.status(400).json({ error: `Missing phone or ${fileField}` });
      }

      const fileBuffer = Buffer.from(rest[fileField], 'base64');
      const mimeMatch = rest[fileField].match(/^data:([^;]+);/);
      const mimeType = mimeMatch ? mimeMatch[1] : 'application/octet-stream';
      const ext = mimeType.split('/')[1] || 'bin';

      const FormData = (await import('form-data')).default;
      const form = new FormData();
      form.append('phone', phone);
      form.append(fileField.replace(/_base64$/, ''), fileBuffer, `file.${ext}`);
      for (const field of fields) {
        if (field !== fileField && rest[field] !== undefined) {
          form.append(field, rest[field]);
        }
      }

      const buffer = form.getBuffer();
      const response = await fetch(`${apiUrl}${gowaPath}`, {
        method: 'POST',
        headers: {
          "Authorization": authHeader,
          "X-Device-Id": deviceId,
          ...form.getHeaders(),
          "Content-Length": String(buffer.length),
        },
        body: buffer
      });
      const data = await response.json();
      res.json(data);
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  };

  // ── Device Management ──
  app.get("/api/whatsapp/device/status", authenticateToken, proxyGet("", (req) => `/devices/${getGoWAHeaders(req.user.uid).deviceId}/status`));
  app.get("/api/whatsapp/device/login", authenticateToken, proxyGet("", (req) => `/devices/${getGoWAHeaders(req.user.uid).deviceId}/login`));
  app.post("/api/whatsapp/device/logout", authenticateToken, proxyPost("", (req) => `/devices/${getGoWAHeaders(req.user.uid).deviceId}/logout`));
  app.post("/api/whatsapp/device/reconnect", authenticateToken, proxyPost("", (req) => `/devices/${getGoWAHeaders(req.user.uid).deviceId}/reconnect`));

  // ── Send (JSON body) ──
  app.post("/api/whatsapp/send/message", authenticateToken, proxyPost("/send/message"));
  app.post("/api/whatsapp/send/contact", authenticateToken, proxyPost("/send/contact"));
  app.post("/api/whatsapp/send/location", authenticateToken, proxyPost("/send/location"));
  app.post("/api/whatsapp/send/poll", authenticateToken, proxyPost("/send/poll"));
  app.post("/api/whatsapp/send/presence", authenticateToken, proxyPost("/send/presence"));
  app.post("/api/whatsapp/send/chat-presence", authenticateToken, proxyPost("/send/chat-presence"));
  app.post("/api/whatsapp/send/link", authenticateToken, proxyPost("/send/link"));

  // ── Send (Multipart via base64 in JSON) ──
  app.post("/api/whatsapp/send/image", authenticateToken, proxyMultipart("/send/image", ["phone", "image_base64", "caption"], "image_base64"));
  app.post("/api/whatsapp/send/file", authenticateToken, proxyMultipart("/send/file", ["phone", "file_base64", "filename"], "file_base64"));
  app.post("/api/whatsapp/send/video", authenticateToken, proxyMultipart("/send/video", ["phone", "video_base64", "caption"], "video_base64"));
  app.post("/api/whatsapp/send/sticker", authenticateToken, proxyMultipart("/send/sticker", ["phone", "sticker_base64"], "sticker_base64"));
  app.post("/api/whatsapp/send/audio", authenticateToken, proxyMultipart("/send/audio", ["phone", "audio_base64"], "audio_base64"));

  // ── Message Actions ──
  app.post("/api/whatsapp/message/:messageId/delete", authenticateToken, proxyPost("", (req) => `/message/${req.params.messageId}/delete`));
  app.post("/api/whatsapp/message/:messageId/revoke", authenticateToken, proxyPost("", (req) => `/message/${req.params.messageId}/revoke`));
  app.post("/api/whatsapp/message/:messageId/react", authenticateToken, proxyPost("", (req) => `/message/${req.params.messageId}/reaction`));
  app.post("/api/whatsapp/message/:messageId/update", authenticateToken, proxyPost("", (req) => `/message/${req.params.messageId}/update`));
  app.post("/api/whatsapp/message/:messageId/read", authenticateToken, proxyPost("", (req) => `/message/${req.params.messageId}/read`));
  app.post("/api/whatsapp/message/:messageId/star", authenticateToken, proxyPost("", (req) => `/message/${req.params.messageId}/star`));
  app.post("/api/whatsapp/message/:messageId/unstar", authenticateToken, proxyPost("", (req) => `/message/${req.params.messageId}/unstar`));

  // ── Chat ──
  app.get("/api/whatsapp/chats", authenticateToken, proxyGet("/chats"));
  app.get("/api/whatsapp/chat/:jid/messages", authenticateToken, proxyGet("", (req) => `/chat/${req.params.jid}/messages`));
  app.post("/api/whatsapp/chat/:jid/pin", authenticateToken, proxyPost("", (req) => `/chat/${req.params.jid}/pin`));
  app.post("/api/whatsapp/chat/:jid/archive", authenticateToken, proxyPost("", (req) => `/chat/${req.params.jid}/archive`));
  app.post("/api/whatsapp/chat/:jid/disappearing", authenticateToken, proxyPost("", (req) => `/chat/${req.params.jid}/disappearing`));

  // ── Groups ──
  app.get("/api/whatsapp/groups", authenticateToken, proxyGet("/user/my/groups"));
  app.post("/api/whatsapp/group/create", authenticateToken, proxyPost("/group"));
  app.post("/api/whatsapp/group/join", authenticateToken, proxyPost("/group/join-with-link"));
  app.get("/api/whatsapp/group/info", authenticateToken, proxyGet("/group/info"));
  app.get("/api/whatsapp/group/preview", authenticateToken, proxyGet("/group/info-from-link"));
  app.get("/api/whatsapp/group/participants", authenticateToken, proxyGet("/group/participants"));
  app.post("/api/whatsapp/group/participants/add", authenticateToken, proxyPost("/group/participants"));
  app.post("/api/whatsapp/group/participants/remove", authenticateToken, proxyPost("/group/participants/remove"));
  app.post("/api/whatsapp/group/participants/promote", authenticateToken, proxyPost("/group/participants/promote"));
  app.post("/api/whatsapp/group/participants/demote", authenticateToken, proxyPost("/group/participants/demote"));
  app.post("/api/whatsapp/group/name", authenticateToken, proxyPost("/group/name"));
  app.post("/api/whatsapp/group/photo", authenticateToken, proxyMultipart("/group/photo", ["group_id", "photo_base64"], "photo_base64"));
  app.post("/api/whatsapp/group/locked", authenticateToken, proxyPost("/group/locked"));
  app.post("/api/whatsapp/group/announce", authenticateToken, proxyPost("/group/announce"));
  app.post("/api/whatsapp/group/topic", authenticateToken, proxyPost("/group/topic"));
  app.get("/api/whatsapp/group/invite-link", authenticateToken, proxyGet("/group/invite-link"));
  app.post("/api/whatsapp/group/leave", authenticateToken, proxyPost("/group/leave"));

  // ── User / Contacts ──
  app.get("/api/whatsapp/contacts", authenticateToken, proxyGet("/user/my/contacts"));
  app.get("/api/whatsapp/user/info", authenticateToken, proxyGet("/user/info"));
  app.get("/api/whatsapp/user/check", authenticateToken, proxyGet("/user/check"));
  app.get("/api/whatsapp/user/avatar", authenticateToken, proxyGet("/user/avatar"));
  app.get("/api/whatsapp/user/business-profile", authenticateToken, proxyGet("/user/business-profile"));
  app.get("/api/whatsapp/user/privacy", authenticateToken, proxyGet("/user/my/privacy"));
  app.post("/api/whatsapp/user/pushname", authenticateToken, proxyPost("/user/pushname"));

  // ── Legacy: single send endpoint (kept for backward compatibility) ──
  app.post("/api/whatsapp/send", authenticateToken, async (req: any, res) => {
    try {
      const { number, message } = req.body;
      if (!number || !message) return res.status(400).json({ error: "Missing 'number' or 'message'" });
      const { apiUrl, deviceId, authHeader } = getGoWAHeaders(req.user.uid);
      const formattedPhone = String(number).replace(/[^0-9]/g, "");
      const response = await fetch(`${apiUrl}/send/message`, {
        method: "POST",
        headers: { "Content-Type": "application/json", "Authorization": authHeader, "X-Device-Id": deviceId },
        body: JSON.stringify({ phone: formattedPhone, message })
      });
      if (!response.ok) throw new Error(`GoWA API error: ${response.status} ${await response.text()}`);
      const data = await response.json();
      const messageId = data.results?.message_id || `msg-${Date.now()}`;
      const ts = Math.floor(Date.now() / 1000);
      await db.collection("whatsapp_messages").add({
        phone: formattedPhone, sender_name: "Me", message_id: messageId, text: message, from_me: true, timestamp: ts,
        created_at: admin.firestore.FieldValue.serverTimestamp()
      }).catch((e: any) => console.error("WhatsApp Firestore save error:", e));
      res.json({ success: true, data });
    } catch (err: any) {
      console.error("WhatsApp Send error:", err.message);
      res.status(500).json({ error: err.message });
    }
  });

  // ── Legacy: Connect/QR (kept for backward compatibility) ──
  app.get("/api/whatsapp/connect", authenticateToken, async (req: any, res) => {
    try {
      const { apiUrl, deviceId, authHeader } = getGoWAHeaders(req.user.uid);
      let stateRes = await fetch(`${apiUrl}/devices/${deviceId}/status`, { headers: { "Authorization": authHeader } });
      let shouldRegister = stateRes.status === 404;
      if (stateRes.status === 500) {
        const txt = await stateRes.text();
        if (txt.toLowerCase().includes("not found")) shouldRegister = true;
      }
      if (shouldRegister) {
        await fetch(`${apiUrl}/devices`, {
          method: "POST", headers: { "Content-Type": "application/json", "Authorization": authHeader },
          body: JSON.stringify({ device_id: deviceId })
        });
        stateRes = await fetch(`${apiUrl}/devices/${deviceId}/status`, { headers: { "Authorization": authHeader } });
      }
      if (!stateRes.ok) throw new Error(`Device status failed: ${stateRes.status}`);
      const status = await stateRes.json();
      if (status.is_logged_in || status.is_connected || status.results?.is_logged_in || status.results?.is_connected) {
        return res.json({ state: "open", details: status });
      }
      const loginRes = await fetch(`${apiUrl}/app/login?device_id=${deviceId}`, { headers: { "Authorization": authHeader } });
      if (!loginRes.ok) {
        const txt = await loginRes.text();
        if (txt.includes("ALREADY_LOGGED_IN")) return res.json({ state: "open" });
        throw new Error(`QR fetch failed: ${loginRes.status} ${txt}`);
      }
      const json = await loginRes.json();
      res.json({ base64: json.results?.qr_link || json.qr_link || json.qr || "" });
    } catch (err: any) {
      res.status(500).json({ error: err.message.includes("fetch failed") ? "GoWA server unreachable." : err.message });
    }
  });

  // ── Webhook Receiver (unauthenticated - called by GoWA) ──
  app.post("/api/whatsapp/webhook", async (req: any, res) => {
    try {
      const { event, payload } = req.body || {};
      console.log(`GoWA webhook event: ${event}`);
      if (event === "message" && payload) {
        const key = payload.key || {};
        const remoteJid = key.remote_jid || "";
        const fromMe = !!key.from_me;
        const messageId = key.id || "";
        const pushName = payload.push_name || "";
        const timestamp = payload.timestamp || Math.floor(Date.now() / 1000);
        const messageObj = payload.message || {};
        const text = messageObj.conversation || messageObj.extendedTextMessage?.text || messageObj.imageMessage?.caption || messageObj.videoMessage?.caption || "";
        const phone = remoteJid.split("@")[0] || "";
        if (phone && (text || messageId)) {
          console.log(`Saving webhook message from ${phone} (${pushName}): ${text}`);
          await db.collection("whatsapp_messages").add({
            phone, sender_name: pushName || phone, message_id: messageId, text, from_me: fromMe, timestamp,
            created_at: admin.firestore.FieldValue.serverTimestamp()
          });
        }
      }
      res.status(200).json({ ok: true });
    } catch (err: any) {
      console.error("Webhook processing error:", err);
      res.status(500).json({ error: err.message });
    }
  });

  // ── Fetch Messages from Firestore ──
  app.get("/api/whatsapp/messages", authenticateToken, async (req: any, res) => {
    try {
      const snapshot = await db.collection("whatsapp_messages").orderBy("timestamp", "asc").limit(200).get();
      const messages = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      res.json(messages);
    } catch (err: any) {
      res.status(500).json({ error: err.message });
    }
  });

  // Blog image search endpoint — proxies free image sources (no API keys exposed to frontend)
  app.post("/api/blog/image", async (req: any, res) => {
    const { query } = req.body;
    if (!query) return res.status(400).json({ error: "Missing query" });
    try {
      // Try Unsplash first (free tier, no key needed for basic search)
      const unsplashUrl = `https://api.unsplash.org/search/photos?query=${encodeURIComponent(query)}&per_page=1&orientation=landscape`;
      const unsplashRes = await fetch(unsplashUrl, {
        headers: { Authorization: 'Client-ID 1dafb8bce78fc67689516820adbaa264f55069973f9f0f74a9b45a6b411f6fa3' }
      });
      if (unsplashRes.ok) {
        const data: any = await unsplashRes.json();
        if (data.results && data.results.length > 0) {
          const img = data.results[0];
          const fullUrl = img.urls?.regular || img.urls?.small || '';
          return res.json({
            url: fullUrl,
            alt: img.alt_description || query,
            source: 'Unsplash',
            photographer: img.user?.name || 'Unknown',
            license: 'Unsplash License (free to use)',
            status: 'attached',
          });
        }
      }
      res.json({ status: 'pending', message: 'No image found from free sources' });
    } catch (err: any) {
      res.json({ status: 'pending', message: err.message });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
    // Vite middleware mode doesn't serve public/ — do it explicitly
    app.use(express.static(path.join(process.cwd(), 'public')));
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*all', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  // Error handling middleware
  app.use((err: any, req: any, res: any, next: any) => {
    console.error("GLOBAL ERROR HANDLER:", err);
    res.status(500).json({ error: "Internal Server Error", details: err.message || String(err) });
  });

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
    console.log(`Firestore integrated for DB storage.`);
  });
}

startServer();
